### ISSUE TITLE
Improve Selection of repositories

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#1]
We should improve the selection of repositories in http://localhost:8080/admin/cla/link

Obvious Problems:
- Can add invalid repositories
- Enter does not select first entry
- Should support scrolling on matched results
- Form submission is disabled for Enter (to avoid Enter submitting form when users try to select first entry)

**Comment by rwinch** [comment]
@bclozel Do you think you could take a look at this as we discussed? You will need to follow the instructions in the README to set up the project. You will also need to authenticate with a GitHub account that has an @pivotal.io email address verified. Let me know if you have any questions.

Thanks!

**Comment by bclozel** [comment]
@rwinch just submitted a PR for this.

Note that I think you already took care of `Form submission is disabled for Enter`; now about the scrolling, I'm not sure what you're referring to.

Let me know and I can improve this PR!

**Comment by rwinch** [comment]
@bclozel Thanks for the PR! I'm going to merge this as is as it improves things drastically. I'm going to create a new ticket that describes in more detail what I mean by the scrolling.
