### ISSUE TITLE
Create a Manual Update of GitHub Status Link

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#102]
It would be nice if the comment on the GitHub Pull Request provided a link to forcibly update the GitHub status. This is nice for users who do not use the links in the Pull Request to sign the CLA

**Comment by mp911de** [comment]
This feature could also be used to re-trigger a commit status update in case something broke during the processing within Pivotal CLA.

**Comment by rwinch** [comment]
This is now done
