### ISSUE TITLE
The Manual Sync URL should not use CLA from the URL

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#110]
Currently the Manual Sync URL is:

```
https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security@pullRequestId=123
```

We should not use the CLA name from the URL. Instead, we should look up the CLA in the github hooks of the Pull Request Hooks of the repository that is referenced. Alternatively, we could validate that the CLA name in the URL matches the CLA in the pull request hooks for the repository.

**Comment by Shredder121** [comment]
Validating sounds best in my opinion.
Just as an added measure.
