### ISSUE TITLE
Improve Bulk Adding GitHub Repositories

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#125]
It would be nice if on the link CLA page (i.e. https://cla.pivotal.io/admin/cla/link) the user could indicate to use all repositories that matched. For example, they might type `spring-projects/` which would match all of the projects within the `spring-projects` organization. Then typing CTRL+A would trigger all of these matches to be added.
# Workaround

An alternative is you can paste a "," separated list of all the repositories you wish to link into the UI. This list can be obtained from anywhere you like.

The easiest way would be to access https://cla.pivotal.io/admin/cla/link/repositories.json within a browser that you have authenticated to. You can then modify the result to include only the repositories you wish to modify.

Alternatively, you could obtain the repository ids using any API you wish. It is important to note that for a repository to be accepted into the UI you must be an admin and a collaborator (this ensure that the UI will be able to setup the WebHook necessary).

**Comment by dsyer** [comment]
CSV seems to work, thanks. Maybe that could be added to the wording on the page with the project picker?

**Comment by rwinch** [comment]
@dsyer Thanks for the feedback. Did you look at the updated page? Perhaps it isn't obvious enough, but if you click the ? in

![image](https://cloud.githubusercontent.com/assets/362503/16733458/4aad86ce-4747-11e6-8264-100eb7b5d236.png)

it describes how to do a bulk update. Did you notice this change? Do you feel this is not obvious enough?

**UPDATE** When I fixed #126 I didn't want to clutter the page too much and that is why it is something you need to click
