### ISSUE TITLE
Thanked for signing the CLA even though I didn't

### ISSUE THREAD

**Issue by wilkinsona** [spring-attic/pivotal-cla#130]
Steps to reproduce:
1. Go to https://cla.pivotal.io
2. Click "Sign Individual CLA"
3. Click back
4. "Thank you for signing the Agreement!" is displayed at the top of the page

I've also seen the thank you appear at the top of the CLA page itself, but I haven't manage to determine the necessary steps to reproduce that reliably.

**Comment by rwinch** [comment]
@wilkinsona Thanks for the report.

Your GitHub account is associated to a `@pivotal.io` email address which is has a corporate agreement. This means that while you haven't signed the individual signature, there is a corporate signature that covers you.

Admittedly the UI is pretty confusing, so I created #131 to make it more obvious what is going on.
