### ISSUE TITLE
Provide a mechanism to indicate that a change is considered obvious

### ISSUE THREAD

**Issue by wilkinsona** [spring-attic/pivotal-cla#132]
It would be handy of a project collaborator could indicate that a change is considered obvious and that the CLA does not need to be signed. Perhaps via a comment directed at `pivotal-issuemaster`:

```
@pivotal-issuemaster This is an obvious fix
```

The CLA bot could then update the PR to remove the failing CLA check and perhaps make a follow-up comment that the CLA doesn't need to be signed after all.

**Comment by Shredder121** [comment]
I'd say this could be done with [`IssueComment`](https://developer.github.com/v3/activity/events/types/#issuecommentevent)s and maybe also [`PullRequestReviewComment`](https://developer.github.com/v3/activity/events/types/#pullrequestreviewcommentevent)s.

Other events (CommitComment) don't have an easy way of getting back to the PR.

**Comment by mp911de** [comment]
Both will work. If the anyone mentions the PR contains an `obvious fix` then we'll skip the CLA check. We add a comment `This Pull Request contains an obvious fix. Signing the Contributor License Agreement not necessary.` if there's a comment from the issue master telling `Please sign...` and we set the state to green with the same message.

Deleting the comment containing `... obvious fix ...` causes the PR to be re-evaluated to require the CLA to be signed.
