### ISSUE TITLE
Only Add GitHub Hook once

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#39]

**Comment by mp911de** [comment]
How about also displaying a table of already linked repos?
![bildschirmfoto 2016-04-07 um 17 25 07](https://cloud.githubusercontent.com/assets/1035015/14356574/ba051052-fce5-11e5-9621-4eba48649ba7.png)

**Comment by rwinch** [comment]
The page already loads pretty slow and looking up all the hooks that have been added would be pretty painful. I think we just search for a hook at the time of clicking Use CLA and update it if the hook already exists.

**Comment by mp911de** [comment]
That's my next one

**Comment by rwinch** [comment]
Fixed via #69
