### ISSUE TITLE
We cannot verify signed legacy CLAs till logged in

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#53]
The only way to check the emails of a user is if we have their access token. This means the user will be prompted to sign the CLA and then authenticate and find out that they have signed it.

We will need a flow that marks the pull request as success

**Comment by mp911de** [comment]
Alternative proposal: How about using the mail address from the commits as a fallback option? If all commits in a particular PR carry the same mail address.

**Comment by rwinch** [comment]
@mp911de Thanks for the feedback. I don't think this will help.

The problem (more clearly defined) is this:

When a pull request is created we receive a [pull request event](https://developer.github.com/v3/activity/events/types/#pullrequestevent). The only user related information in the event that we get is the GitHub username / id.

If the user signed a CLA in a legacy system (i.e. Spring's CLA) that only contains first name, last name, and email.

We cannot link the user who signed the CLA to the user in the pull request event. This is because there is no common information between the two. Furthermore, we cannot use the GitHub API to access the user's email address because it is not exposed to us unless we have an access token from that user.

If the user has authenticated with our system, we would have been able to either store an access token for retrieving the emails or the emails themselves. At that point when we receive the GitHub event we will be able to link the event and the legacy CLA via the email address.

When a user who signed in the legacy system authenticates for the first time, we will need to ensure to mark their pull request as successful at the time of authentication (right now we only update the pull request at the time of signing).

**Comment by mp911de** [comment]
About this flow: How about adding two further elements:
1. A dashboard page where the user can see his signed CLA's
2. Add a migration element so if the user is sent to the sign CLA page we can then tell him in a note: "Thanks, we migrated your old signature to the new system, now you can proceed"

The migration step would then also update the PR (which is the missing part to get it working).

**Comment by rwinch** [comment]
@mp911de Thanks for the reply. 

> A dashboard page where the user can see his signed CLA's

I actually just removed the dashboard page as this seemed to clutter things up and not really provide value for any workflows. See #50 I'd be interested in your take as to why we should have a dashboard.

> Add a migration element so if the user is sent to the sign CLA page we can then tell him in a note: "Thanks, we migrated your old signature to the new system, now you can proceed"

I think I have a solution for this. The part I'm having a bit of trouble swallowing is that we will need to update the state of the GitHub PR on a Git.

I'm going to go ahead and assign this one to me as I think I have it mostly sorted out in my head

**Comment by rwinch** [comment]
We have done all we can here
