### ISSUE TITLE
Force refresh of GitHub repositories

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#6]
We cache the GitHub repositories lookup in the browser local storage for the Repository search on the Link to CLA form. This is nice because it takes a long time to lookup the GitHub repositories. However, there are likely instances the user will want to force a refresh. It would be nice if we had a way for the user to easily force a refresh.

**Comment by rwinch** [comment]
@bclozel Any chance you could look into this?

**Comment by bclozel** [comment]
Hey @rwinch, this should be an easy feature to add.

We could add a button or link in that page for this, but I didn't find a proper place for that button (at least one that wouldn't confuse users; and UX is not my forte).

Or we can tweak the cache TTL and make it shorter. Right now by default this value is set to a day.

What do you think?

**Comment by rwinch** [comment]
@bclozel Thanks for the response. I'm not a UX expert either, but I was thinking we could use [Twitter's](http://getbootstrap.com/components/) `glyphicon glyphicon-refresh` as an icon on the right hand side of the Repository input field or perhaps the label. I'm guessing users would figure that out if they are unable to find their repository listed. What do you think?

**Comment by rwinch** [comment]
@bclozel How does bf83cf0 resolve this issue? More specifically, how do I refresh the repositories that are listed without waiting for the expiration.

**Comment by bclozel** [comment]
I've created a new PR for this.
I didn't include that in the first place, because the list of repositories is not cached between browser sessions (i.e. browser tabs). Closing/reopening a tab clears the local cache.

This button forces the refresh anyway.

**Comment by rwinch** [comment]
Thanks! I had thought I tried that and it wasn't working. However, I must have been mistaken. Thanks for the PR!
