### ISSUE TITLE
Github organization on CCLA page has no label/value

### ISSUE THREAD

**Issue by mp911de** [spring-attic/pivotal-cla#66]
Location: sign/pivotal/ccla
Content: `<option value=""></option>`

![bildschirmfoto 2016-04-09 um 16 50 01](https://cloud.githubusercontent.com/assets/1035015/14404334/44c0d30a-fe73-11e5-844d-c8b4d2a65880.png)

**Comment by rwinch** [comment]
Thanks for the report! We should probably make the label something like "Please select an Organization".
