### ISSUE TITLE
Allow Update of CLA

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#8]
When a CLA is updated, it should remember that users signed it but also require an updated signature

**Comment by mp911de** [comment]
Requires a `signedVersion` property in `CorporateSignature`/`IndividualSignature` and setting the commit status to `pending` with a hint of "You need to signed the updated CLA..." (copy to be defined)?

**Comment by rwinch** [comment]
Right now we link to a specific id of the CLA. So what we will probably do is add a property to the CLA that indicates it does not count for a signature anymore.

**Comment by rwinch** [comment]
I should add this one is a pretty low priority as the Spring CLA has never been updated.

**Comment by rwinch** [comment]
We discussed this and we do not require resigning of the CLA at this time. Closing for now
