### ISSUE TITLE
deploy.gradle should switch to cla.pivotal.io as well

### ISSUE THREAD

**Issue by rwinch** [spring-attic/pivotal-cla#91]
Right now we use pivotal-cla.cfapps.io for the URL. However, we really need to deploy to cla.pivotal.io for the production app.

**Comment by rwinch** [comment]
@mp911de Any thoughts on this?

**Comment by mp911de** [comment]
The Gradle 1.1.2 and 1.1.3 plugin call the [deprecated domains for Space URI](https://apidocs.cloudfoundry.org/236/spaces/list_all_domains_for_the_space_%28deprecated%29.html) to obtain a list of domains. The response is:

Request URI: `GET /v2/spaces/…/domains?inline-relations-depth=1`

Response:

```
{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "fb6bd89f-2ed9-49d4-9ad1-97951a573135",
        "url": "/v2/domains/fb6bd89f-2ed9-49d4-9ad1-97951a573135",
        "created_at": "2013-05-04T00:29:46Z",
        "updated_at": null
      },
      "entity": {
        "name": "cfapps.io",
        "router_group_guid": null,
        "router_group_type": null
      }
    }
  ]
}
```

Calling `GET /v2/domains` returns the full list of domains.
